version: 0.1.{build}

skip_non_tags: true

image: Visual Studio 2017
platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'
  - '%USERPROFILE%\AppData\Local\Yarn\cache'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 14 x64
  - git reset --hard HEAD
  - yarn
  - node --version

build_script:
  - yarn version --no-git-tag-version --new-version %APPVEYOR_REPO_TAG_NAME%
  - yarn build

test: off

artifacts:
  - path: build/*.exe
    name: binary

deploy:
  # Deploy to GitHub Releases
  - provider: GitHub
    artifact: binary
    draft: true
    prerelease: false
    auth_token:
      secure: 29CVDRQy0kqoA8UmgE57r0r2B2x2Ax5FmXLXaqlvXapDH4PBXvxP522sxp4qRIEv
    on:
      branch: master # release from master branch only
      APPVEYOR_REPO_TAG: true # deploy on tag push only
